### PR TITLE
Use patch command at first

### PR DESCRIPTION
**Pull request by iGerchak**
### Description
On Magento 2.3.6 Open Source we had an issue when the patch MDVA-31168-V2 was silently failing with no changes in code. During debug session together with @ihor-sviziev we found that it executes the following command:
```bash
cat - <<'EOF' | git apply
diff --git a/vendor/magento/module-downloadable-import-export/Model/Export/RowCustomizer.php b/vendor/magento/module-downloadable-import-export/Model/Export/RowCustomizer.php
index daa874e829e..3b805fef734 100644
--- a/vendor/magento/module-downloadable-import-export/Model/Export/RowCustomizer.php
+++ b/vendor/magento/module-downloadable-import-export/Model/Export/RowCustomizer.php
@@ -82,7 +82,7 @@ class RowCustomizer implements RowCustomizerInterface
             ->addAttributeToSelect('samples_title');
         // set global scope during export
         $this->storeManager->setCurrentStore(Store::DEFAULT_STORE_ID);
-        foreach ($collection as $product) {
+        foreach ($productCollection as $product) {
             $productLinks = $this->linkRepository->getLinksByProduct($product);
             $productSamples = $this->sampleRepository->getSamplesByProduct($product);
             $this->downloadableData[$product->getId()] = [];
EOF
```

After adding `-v` argument - we found the following error, with 0 return code:
`Skipped patch 'vendor/magento/module-downloadable-import-export/Model/Export/RowCustomizer.php'.`
image

During some googling, I found that sometimes it's happening and it's recommended to use patch command instead:
https://stackoverflow.com/questions/42386491/git-apply-skips-patches

So my suggestion is to use `patch` command at first with a fallback to the git apply.

Note: `git --version` output:
git version 2.20.1

Also reproducting on git version 2.27.0

### Fixed Issues (if relevant)

1. magento/magento-cloud-patches#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Release notes

For user-facing changes, add a meaningful release note. For examples, see [Magento Cloud Patches release notes](https://devdocs.magento.com/cloud/release-notes/mcp-release-notes.html).

### Associated documentation updates

Add link to Magento DevDocs PR or Issue, if needed.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] Pull request introduces user-facing changes and includes meaningful updates for any required release notes and documentation changes
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)

### CODE REVIEW

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@oshmyheliuk could you review this PR?

**Comment by bubasuma** [comment]
Hi @iGerchak 
I couldn't reproduce this issue in 2.3.6. I applied the patch using command `./vendor/bin/magento-patches apply MDVA-31168-V2`. The patch was successfully applied  and I could see the changes applied in /vendor/magento/module-downloadable-import-export/Model/Export/RowCustomizer.php:85.

Could you please help us to reproduce this issue?

Here is my concern about the proposed solution

There is no guarantee that there won't be other issues with PATCH and we won't be switching back and forth. Moreover, I don't know any reliable resources that suggest PATCH over GIT for applying patches. Maybe we should think of making it configurable (e.g using environment variable). Perhaps, we should handle this specific issue in GitDriver and consider it as a failure so it will fallback to PATCH?

**Comment by ihor-sviziev** [comment]
Hi,
We were having issue with magento installation that is installed through
composer and added to git repository. Please check that

**Comment by ihor-sviziev** [comment]
@bubasuma any updates? We're having this issue both on Ubuntu based local machine and on CI/CD.

We're running apply command on top of checked out git repository. If you're not able to reproduce it - please contact me in slack - it will be much more effective

**Comment by bubasuma** [comment]
Hi @ihor-sviziev 
I still can't reproduce this issue. Please see attached screenshot
Magento Version: 2.3.6
OS: Ubuntu 20.04
GIT: 2.25.1

### Before Apply
Screen Shot 2021-01-06 at 9 45 47 AM

### After Apply
Screen Shot 2021-01-06 at 9 44 31 AM

### After Revert
Screen Shot 2021-01-06 at 9 46 55 AM

**Comment by ihor-sviziev** [comment]
@bubasuma will try to provide you more details next week

**Comment by bubasuma** [comment]
@ihor-sviziev Could you please also check if there are other patches with the same issue in your environment?

**Comment by viktym** [comment]
@ihor-sviziev please try to modify the patch header.
Example:
replace
> diff --git a/vendor/magento/module-negotiable-quote/Model/NegotiableQuoteConverter.php b/vendor/magento/module-negotiable-quote/Model/NegotiableQuoteConverter.php
> index 050f3f6d4..9a918c0c5 100644

with

> diff  -Nuar a/vendor/magento/module-negotiable-quote/Model/NegotiableQuoteConverter.php b/vendor/magento/module-negotiable-quote/Model/NegotiableQuoteConverter.php

and apply using Git

**Comment by ihor-sviziev** [comment]
@viktym will try that one as well

**Comment by ihor-sviziev** [comment]
Hi @viktym and @bubasuma,
Changing `diff --git` to the `diff -Nuar` did the job! 👍 

I executed following commands:
```bash
head -n1 vendor/magento/quality-patches/patches/os/MDVA-30942__fixes_performance_when_exporting_100k_products_using_consumers__2.3.5-p2.patch
php vendor/bin/magento-patches apply MDVA-31168-V2
php vendor/bin/magento-patches status | grep MDVA-31168-V2
```

Before changing:
image
❌ the patch not applied (and I checked it in the code)

After:
image
✔ the patch is applied (and I checked it in the code)

It seems like a correct fix for this issue will be going through all the patches in https://github.com/magento/quality-patches/tree/master/patches and replace `diff --git` with `diff -Nuar`

**Comment by ihor-sviziev** [comment]
Also, let's introduce a feature that will prevent such an issue in the future, maybe adjusting the following check to check if it's not in the working tree using `git rev-parse --is-inside-work-tree`?
https://github.com/magento/magento-cloud-patches/blob/04156562ba97aba766d52149d091b55adef9a558/src/Shell/Command/GitDriver.php#L87-L97
Similar to this https://github.com/vaimo/composer-patches/blob/2295a6696534ef9e0eaa7c7f50e1b9ddb0aacae9/src/Config/Defaults.php#L40

**Comment by oshmyheliuk** [comment]
@viktym @ihor-sviziev @bubasuma @iGerchak 
As I understand the problem was solved and we can close this PR?

**Comment by ihor-sviziev** [comment]
It wasn’t fixed. Please review my recent comments

**Comment by oshmyheliuk** [comment]
@bubasuma @viktym 
Could you please take a look?

**Comment by bubasuma** [comment]
@oshmyheliuk I think the issue still exists although we're not able to reproduce it. But as suggested @ihor-sviziev, the correct fix would be to replace `diff --git` with `diff -Nuar` in all patches https://github.com/magento/quality-patches/tree/master/patches. The proposed changes in this pull request is not a proper fix for this issue.

**Comment by oshmyheliuk** [comment]
@bubasuma thanks for the clarification. 
So, your team is going to update patches in `quality-patches` repo?

@iGerchak I'm closing this pr as the fix will be done in a different repository. Feel free to reopen or create a new pull request.
Thanks for your contribution.

**Comment by viktym** [comment]
@ihor-sviziev thanks for raising it up, investigation, and valuable advices
I'll create a task to fix this issue. 
Will be fixed in 'magento/quality-patches' v.1.0.15

**Comment by viktym** [comment]
@ihor-sviziev is it enough to replace `diff --git` with `diff -Nuar` or need to strip `index 050f3f6d4..9a918c0c5 100644` as well in your case ?

**Comment by ihor-sviziev** [comment]
@viktym, it was enough to replace just a first line. 

I'm curious that potentially this issue might appear again if we do not introduce some prevention mechanism, like checking inside the working tree. What do you think about it? You can see in my previous comments more details about that

**Comment by viktym** [comment]
@ihor-sviziev thanks for this tip
My concern is that on Cloud we are always inside the working tree during the 'Build' phase, so 'patch' becomes a default command for Cloud.
So my plan is to update diff's header for current patches in https://github.com/magento/quality-patches/tree/master/patches
and implement replacing `diff --git` with `diff -Nuar` (if any) on a fly just before applying the patch content.

**Comment by ihor-sviziev** [comment]
@viktym cool. Thank you!
Do we have created an issue for tracking status for those 2 things?

**Comment by viktym** [comment]
@ihor-sviziev patches from https://github.com/magento/quality-patches/tree/master/patches are already updated and released in 'magento/quality-patches':1.0.14 (please update magento/quality-patches package on your instances)
MC-40529 is a ticket about replacing 'diff --git' with 'diff -Nuar'  before applying the patch (implementation in magento/magento-cloud-patches). Target release - 1.0.9.

**Pull request closed without merging**
