### PR TITLE
MC 37324: Add fallback to 'patch' command when 'git' command is not available

### PR DESCRIPTION
**Pull request by BaDos**
### Description
As a Magento OnPrem Customer, I want to be able to apply patches with '[patch](https://en.wikipedia.org/wiki/Patch_(Unix))' command if I don't have  '[Git](https://git-scm.com/)' installed.

Currently, we have a [recommendation](https://support.magento.com/hc/en-us/articles/360028367731)  to use '[patch](https://en.wikipedia.org/wiki/Patch_(Unix))' command for patch applying. So probably some OnPrem customers don't have installed  '[Git](https://git-scm.com/)'  and can't use MQP tool.

### Fixed Issues (if relevant)

[MC 37324](https://jira.corp.magento.com/browse/MC-37324): Add fallback to 'patch' command when 'git' command is not available

https://jira.corp.magento.com/browse/MCLOUD-7069 

#### Scenario 1 (GIT is installed, PATCH is installed)
Check that GIT is used to apply/revert patches and

 - [ ] Check that patch can be applied/reverted
 - [ ] Check that correct status is shown for patches in patch list (_vendor/bin/magento-patches status_)
 - [ ] Check that error message is shown if patch cannot be applied/reverted for some reason (e.g conflict)

#### Scenario 2 (GIT is not installed, PATCH is installed)
Check that PATCH is used to apply/revert patches and

 - [ ] Check that patch can be applied/reverted
 - [ ] Check that correct status is shown for patches in patch list (_vendor/bin/magento-patches status_)
 - [ ] Check that error message is shown if patch cannot be applied/reverted for some reason (e.g conflict)

#### Scenario 2 (GIT is not installed, PATCH is not installed)
Check that PATCH is used to apply/revert patches and

 - [ ] Check that patch cannot be applied/reverted and error message is shown to user that PATCH or GIT is required to apply/revert patches.

### Release notes

[Unix Patch](https://en.wikipedia.org/wiki/Patch_(Unix)) command is now used to apply patches if GIT is not available.

### Associated documentation updates

None

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] Pull request introduces user-facing changes and includes meaningful updates for any required release notes and documentation changes
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)

### CODE REVIEW

**Comment by bubasuma** [comment]
@NadiyaS @bbatsche 
Have you had a chance to look at this?

**Review by NadiyaS — APPROVED** [review]

**Review by bbatsche — APPROVED** [review]

**Comment by andriyShevtsov** [comment]
QA approved

**Comment by NadiyaS** [comment]
@magento import pr to magento-commerce/magento-cloud-patches

**Comment by magento-engcom-team** [comment]
@NadiyaS the pull request successfully imported.

**Pull request merged**
