### PR TITLE
Restrict patch from being applied to version 2.4.3-p2. Since it's bee…

### PR DESCRIPTION
**Pull request by leonhelmus**
…n resolved in the patch it self.

For more information see:
* https://github.com/magento/magento2/issues/35341

### Description
Magento cloud patches apply a patch that has been resolved in magento 2.4.3-p2. According to @nathanjosiah. 

### Fixed Issues (if relevant)
1. Patch MDVA-43443__parser_token_new_fix__2.4.3.patch is not applied for 2.4.3-p2.

### Associated documentation updates
https://github.com/magento/magento2/issues/35341

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] Pull request introduces user-facing changes and includes meaningful updates for any required release notes and documentation changes
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)

### CODE REVIEW

**Comment by leonhelmus** [comment]
I cannot resolve this issue for php7.2 in my opinion. Could someone check it?

**Comment by leonhelmus** [comment]
@BarnyShergold i saw you were a pr of the previous merge. Could you look into this? I think it's important otherwise all cloud project will have a patch that should not be applied from @nathanjosiah

**Comment by BarnyShergold** [comment]
> @BarnyShergold i saw you were a pr of the previous merge. Could you look into this? I think it's important otherwise all cloud project will have a patch that should not be applied from @nathanjosiah
Not sure which merge you are referring to? Please can you provide a link and clarify what you want me to look into? Cheers

**Comment by leonhelmus** [comment]
@BarnyShergold the functional check doesnt seem to work for php7.2. While i dont think i did anything wrong. I just wanted to bring this too urgent notice and with the last merge i mean a previous pr that was merged in this repository. Also you helped me last time i created an pr for ece-tools. Thats why i asked you 😁.

The constraint that i changed is from smaller than 2.4.3-p3 to smaller than 2.4.3-p2 is necessary. Nathan confirmed to me that this patch must not be applied for magento projects that are on 2.4.3-p2. Since it was resolved in a different way in 2.4.3-p2. I think this issue has a high priority because it must not be applied for magento 2.4.3-p2 cloud projects, while it does now. So everyone that now updates to 2.4.3-p2 will have a wrong patch added to their shop. For more info about this patch see https://github.com/magento/magento2/issues/35341


Hope this clarifies my issues. Also cant seem to add any assignees to check this pr.

**Comment by BarnyShergold** [comment]
> @BarnyShergold the functional check doesnt seem to work for php7.2. While i dont think i did anything wrong. I just wanted to bring this too urgent notice and with the last merge i mean a previous pr that was merged in this repository. Also you helped me last time i created an pr for ece-tools. Thats why i asked you 😁.
> 
> The constraint that i changed is from smaller than 2.4.3-p3 to smaller than 2.4.3-p2 is necessary. Nathan confirmed to me that this patch must not be applied for magento projects that are on 2.4.3-p2. Since it was resolved in a different way in 2.4.3-p2. I think this issue has a high priority because it must not be applied for magento 2.4.3-p2 cloud projects, while it does now. So everyone that now updates to 2.4.3-p2 will have a wrong patch added to their shop. For more info about this patch see [magento/magento2#35341](https://github.com/magento/magento2/issues/35341)
> 
> Hope this clarifies my issues. Also cant seem to add any assignees to check this pr.

I'm afraid I can't help you with the functional tests - it won't say why it's failed and I can't see any reason . I'll see if it possible to re-run but you'll have to wait for one of the main people to review.

**Comment by BarnyShergold** [comment]
@magento run Functional Tests

**Comment by leonhelmus** [comment]
Could anyone look at this i think it's pretty important.

**Comment by hostep** [comment]
In the line above the line you modified, the version should probably also be changed from `<2.3.7-p4` to `<2.3.7-p3`, no? @nathanjosiah can maybe confirm?

**Comment by BaDos** [comment]
Hi @leonhelmus 
Thank you for your contribution.
I'm going to process this PR.
FT was fixed yesterday.

**Comment by BaDos** [comment]
@magento import pr to magento-commerce/magento-cloud-patches

**Comment by m2-github-services** [comment]
@BaDos the Pull Request is successfully imported.

**Comment by m2-github-services** [comment]
@BaDos an error occurred during the Pull Request import.

**Comment by leonhelmus** [comment]
When will the tag 1.0.17 be available?

**Comment by leonhelmus** [comment]
@BaDos  I really want to update to 1.0.17

**Comment by leonhelmus** [comment]
@nathanjosiah  Could someone make the tag available?

**Comment by BaDos** [comment]
@leonhelmus https://github.com/magento/magento-cloud-patches/tree/1.0.17
also, repo.magento.com has this version

**Comment by leonhelmus** [comment]
@BaDos  thanks for the update :). This will prevent other people from applying the patch.

**Pull request merged**
