### PR TITLE
BUNDLE-2554: Updating patch to match hotfix patch

### PR DESCRIPTION
**Pull request by magterskine**
- This change only modifys composer versions. No functional change.

### CODE REVIEW

**Review by bbatsche — COMMENTED** [review]
This strikes me as a remarkably brittle solution to the underlying problem. Like, the first time anybody runs `composer update` on their project this patch could become more or less permanently broken.

**Review by bbatsche — CHANGES_REQUESTED** [review]
Also this patch won't actually be effective in getting the correct requirements installed. The actual installed packages is based on the project's `composer.lock` file (not the `composer.json` files in individual packages), and are installed _before_ any patching operation could be performed anyways

**Comment by shiftedreality** [comment]
@magterskine we apply patches after Composer dependencies were installed, so this change does not have any result.

**Comment by shiftedreality** [comment]
@magterskine I'm closing this issue, please let us know if this still makes value

**Pull request closed without merging**
